#!/bin/sh

if [[ $EUID != 0 ]] ; then
  echo This must be run as root!
  exit 1
fi

USB_DRIVERS_PATH="/sys/bus/usb/drivers/usb"

if ! cd $USB_DRIVERS_PATH ; then
  echo Weird error. Failed to change directory to $USB_DRIVERS_PATH
  exit 1
fi

echo Resetting TypeC from $USB_DRIVERS_PATH...

#Assuming that USB type C 2.0 is always 1-1
#and 3.0 is 2-1
echo -n "1-1" > unbind
sleep 0.5
echo -n "1-1" > bind

