#!/bin/sh

#bt_serial=$1
bt_serial=/dev/ttyPS1
bt_serial_log=/dev/ttyPS0

2>$bt_serial_log #redirect stderr

stty -F $bt_serial 115200 cs8 -cstopb -parenb -echo

led(){
	uio-test -t led -i $1 > $bt_serial_log
}

timeout_test(){
	sleep $1 > $bt_serial_log
	kill $2 > bt_serial_log;
}

btn() {
	uio-test -t btn -i C&
	test_pid=$!
	timeout_test 10 $test_pid &
	wait $test_pid
}

debug() {
	echo debug: "$1" > /dev/ttyPS0
}

test1(){
	debug "test1";
}

running(){
	debug "running";
}

run_command () {
	cmd=$1
	cmd=$(echo -e -n $cmd | sed 's/\r$//')
	$cmd;
	rc=$?
	debug "code:$rc";
	case $rc in
		0)
			echo PASS > $bt_serial
			debug "$cmd ok";
			;;
		127)
			echo FAIL > $bt_serial;
			debug "Command '$cmd' is not implemented!";
			;;
		*)
			echo FAIL > $bt_serial;
			debug "Command '$cmd' unknown issue:$rc";
			;;
	esac
}
echo RUNNING > $bt_serial_log
while read command; do run_command "$command"; done < $bt_serial;
