#!/bin/sh

#bt_serial=$1
bt_serial=/dev/ttyPS1
stty -F $bt_serial 115200 cs8 -cstopb -parenb -echo

led(){
	uio-test -t led -i $1
}

timeout_test(){
	sleep $1;
	kill $2;
}

btn() {
	uio-test -t btn -i C&
	test_pid=$!
	timeout_test 10 $test_pid &
	wait $test_pid
}

debug() {
	echo debug: "$1" > /dev/ttyPS0
}

test1(){
	debug "test1";
}

running(){
	debug "running";
}

sysmon(){
	debug "bist:sysmon";
	vccvpvn=$(command sysmon -v vccvpvn -- /sys/bus/iio/devices/iio\:device0);
	rc=$?
	#sysmon will return the voltage in mV across pins VP and VN
	#the test fixture will generate a voltage of 520.5 mV nominal
	if [[ $rc -eq 0 && $(bc <<< "$vccvpvn < 543 && $vccvpvn > 498") -eq 1 ]]; then
		echo PASS > $bt_serial
	else
		debug "rc:$rc, vccvpvn:$vccvpvn" 
		echo FAIL > $bt_serial
	fi;
}

run_command () {
	cmd=$1
	$cmd;
	rc=$?
	[ $rc -eq 0 ] && echo PASS > $bt_serial || echo FAIL > $bt_serial;
	[ $rc -eq 0 ] && debug "$cmd sucessful run" || debug "Command '$cmd' is not implemented! code:$rc";

}

while read command; do run_command "$command"; done < $bt_serial;
