#!/bin/sh

#bt_serial=$1
bt_serial=/dev/ttyPS1
stty -F $bt_serial 115200 cs8 -cstopb -parenb -echo

led(){
	uio-test -t led -
}
debug(){
	echo debug: "$1"
}

test1(){
	debug "test1";
}

running(){
	debug "running";
}

run_command () {
	cmd=$1
	#echo "$cmd you mean" > $bt_serial;
	$cmd;
	rc=$?
	[ $rc -eq 0 ] && echo PASS > $bt_serial || echo FAIL > $bt_serial;
	[ $rc -eq 0 ] && debug "$cmd sucessful run" || debug "Command '$cmd' is not implemented! code:$rc";

}

while read command; do run_command "$command"; done < $bt_serial;
