/*  pwm-rgb-led.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include<linux/module.h>
#include<linux/moduleparam.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("pwm-rgb-led - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "pwm-rgb-led"
/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */

u32 *pwm_reg0;


unsigned int pwm_color_fill = 0x00000000;
//module_param(pwm_color_fill, uint, S_IRUGO | S_IWUSR);

// calback on param change
int notify_param(const char *val, const struct kernel_param *kp)
{
	int res = param_set_int(val, kp);
	if(res == 0 ) {
		//printk("module params changed pwm_en:%d\n", pwm_en);
		//printk("Module parameters were changed (0x%08x)\n", pwm_color_fill);
		*pwm_reg0 = pwm_color_fill;
		//printk("pwm_reg 0x%08x\n", *pwm_reg0);
		return 0;
	}
	return -1;
}

const struct kernel_param_ops pwm_rgb_led_param_ops =
{
	.set = &notify_param, // Use our setter ...
	.get = &param_get_int, // .. and standard getter
};

//module_param_cb(pwm_en, &pwm_rgb_led_param_ops, &pwm_en, S_IRUGO|S_IWUSR );
module_param_cb(pwm_color_fill, &pwm_rgb_led_param_ops, &pwm_color_fill, S_IRUGO|S_IWUSR );
// end of calback on param change

struct pwm_rgb_led_local {
	//int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

/*
static irqreturn_t pwm_rgb_led_irq(int irq, void *lp)
{
	printk("pwm-rgb-led interrupt\n");
	return IRQ_HANDLED;
}
*/

static int pwm_rgb_led_probe(struct platform_device *pdev)
{
	//struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct pwm_rgb_led_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct pwm_rgb_led_local *) kmalloc(sizeof(struct pwm_rgb_led_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate pwm-rgb-led device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "pwm-rgb-led: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	/*
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "pwm-rgb-led at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &pwm_rgb_led_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}
	dev_info(dev,"pwm-rgb-led at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	*/

	dev_info(dev,"pwm-rgb-led at 0x%08x mapped to 0x%08x",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr);

	pwm_reg0 = (u32*) lp->base_addr;

	return 0;
error3:
	//free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int pwm_rgb_led_remove(struct platform_device *pdev)
{

	struct device *dev = &pdev->dev;
	struct pwm_rgb_led_local *lp = dev_get_drvdata(dev);
	//free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id pwm_rgb_led_of_match[] = {
	{ .compatible = "digilent,pwm-rgb-led", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, pwm_rgb_led_of_match);
#else
# define pwm_rgb_led_of_match
#endif


static struct platform_driver pwm_rgb_led_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= pwm_rgb_led_of_match,
	},
	.probe		= pwm_rgb_led_probe,
	.remove		= pwm_rgb_led_remove,
};

static int __init pwm_rgb_led_init(void)
{
	printk("<1>Digilent pwm module loaded.\n");
//	printk("<1>Module parameters were (0x%02x) (0x%02x) (0x%02x)\n", pwm_red_fill, pwm_green_fill,
//			pwm_blue_fill);

	return platform_driver_register(&pwm_rgb_led_driver);
}


static void __exit pwm_rgb_led_exit(void)
{
	platform_driver_unregister(&pwm_rgb_led_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(pwm_rgb_led_init);
module_exit(pwm_rgb_led_exit);
